Add nodejs v14.17.6
kubesphere/devops-agent pull request #40
Opened 2021-09-17 01:22 UTC by LinuxSuRen

fix #15
fix #16

2021-09-23 15:23 UTC, JohnNiang commented
/lgtm

2022-02-20 15:36 UTC, JohnNiang requested changes

2022-02-20 15:36 UTC, JohnNiang commented on .github/workflows/build-podman.yaml
> +      if: github.event_name != 'pull_request'
Please refer to the custom GitHub Action to config the pipeline as follows:
https://github.com/kubesphere/devops-agent/blob/46d0e88a353dae4669386baf16d7241dd6a5039a/.github/workflows/build-podman.yaml#L119-L134

2022-08-03 07:17 UTC, LinuxSuRen commented
We have a better solution to maintaining the Jenkins agent images. See also https://github.com/kubesphere/devops-agent/issues/75

/close

2022-08-03 07:17 UTC, closed without merging